# Biblioteca NumPy:

- Funções: https://numpy.org/doc/2.1/reference/routines.math.html

### Estrutura de Memória
- **Listas do Python**: Estrutura baseada em **array dinâmico** que armazena referências no heap.
- **NumPy Arrays**: Dados contíguos na memória, acessados por aritmética de ponteiros.


In [1]:

# Importando a biblioteca
import numpy as np


### Formas de inicialização


In [4]:
# Criar um array com diferentes métodos
## a partir de uma lista
array_list = np.array([1,2,3,4])
print(array_list)
type(array_list)

[1 2 3 4]


numpy.ndarray

In [5]:
#especificar o tipo de dado
array_float = np.array([1,2,3,4], dtype= float)
print(array_float)

[1. 2. 3. 4.]


In [7]:
# gerar com valores constantes
# zeros
array_zeros = np.zeros(5)
print(array_zeros)

#uns
array_uns = np.ones(5)
print(array_uns)

# genérico para qualquer valor
array_generic = np.full(5,7)
print(array_generic)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[7 7 7 7 7]


In [8]:
#gerar um array no formato de sequência
array_seq = np.arange(10)
print(array_seq)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# gerar números aleatórios
## random.rand (continuos)
## random.radint (inteiros)
## random.randn (distribuição normal)
## random.choice (gera repetições aleatórias a partir de uma lista)

print(np.random.rand(5))
print(np.random.randint(0,10, size= 5)) #intervalo de 0 a 10 escolher 5 números
print(np.random.randn(5))
print(np.random.choice([20, 30, 40, 50], size= 5))

[0.25792284 0.95292247 0.2842116  0.16944869 0.2935682 ]
[8 2 2 3 0]
[-0.50555686 -1.74220897  0.44846766  1.06460286  0.51293775]
[50 30 50 50 50]


## Operações com NumPy

### Estatísticas com NumPy

In [14]:

# Gerar um array aleatório com 20 números e calcular média, desvio padrão e variância.
array_exemplo = np.random.randint(0, 100, size= 10)
print(array_exemplo)
print(f'Média: {np.mean(array_exemplo)}')
print(f'Desvio Padrão: {np.std(array_exemplo)}')
print(f'Variância: {np.var(array_exemplo)}')

[14 35  8 99 17  0  0 85 59 74]
Média: 39.1
Desvio Padrão: 35.31132962662267
Variância: 1246.8899999999999


### Operações aritméticas ou lógicas entre arrays

In [16]:

# Multiplicar cada elemento de um array por um número escalar.
array_int = np.arange(0,10)
array_mult = array_int * 10
print(array_int)
print(array_mult)

[0 1 2 3 4 5 6 7 8 9]
[ 0 10 20 30 40 50 60 70 80 90]


### Operações Condicionais

In [21]:

# Criar um array de números e filtrar os valores maiores que 5.
array_int = np.random.randint(0, 15, size= 10)
filtro_array = array_int > 5
print(array_int)
print(filtro_array)
print(array_int[filtro_array])

[ 1  3  9  2  1 14 12  7  6 11]
[False False  True False False  True  True  True  True  True]
[ 9 14 12  7  6 11]
